version: '3'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d lms_db -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8001:8000'
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    env_file:
      - .env
    
    depends_on:
      - redis
      - app
  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -S django
    env_file:
      - .env
    depends_on:
      - redis
      - app

volumes:
  pg_data: