# Generated by Django 5.0.4 on 2024-04-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_course_price_lesson_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, null=True, verbose_name='id сессии stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'оплачено'), ('unpaid', 'ожидает оплаты')], default='unpaid', max_length=20, verbose_name='статус'),
        ),
    ]
