# Generated by Django 5.0.4 on 2024-04-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_payment_session_id_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
    ]
